In [215]:
import numpy as np
import pandas as pd

In [216]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [217]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [218]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [219]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [220]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [221]:
targets.shape

(700,)

In [222]:
#data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

## iteration 2, remove additional variables without much significance

In [223]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Distance to Work', 'Daily Work Load Average'], axis=1)

In [224]:
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [225]:
data_with_targets.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Transportation Expense  \
0        0        0        0        1            7                     289   
1        0        0        0        0            7                     118   
2        0        0        0        1            7                     179   
3        1        0        0        0            7                     279   
4        0        0        0        1            7                     289   

   Age  Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0   33               30          0         2     1                      1  
1   50               31          0         1     0                      0  
2   38               31          0         0     0                      0  
3   39               24          0         2     0                      1  
4   33               30          0         2     1                      0

In [226]:
data_with_targets is data_preprocessed

False

In [227]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Transportation Expense  \
0        0        0        0        1            7                     289   
1        0        0        0        0            7                     118   
2        0        0        0        1            7                     179   
3        1        0        0        0            7                     279   
4        0        0        0        1            7                     289   

   Age  Body Mass Index  Education  Children  Pets  
0   33               30          0         2     1  
1   50               31          0         1     0  
2   38               31          0         0     0  
3   39               24          0         2     0  
4   33               30          0         2     1

## Standarize Data

In [228]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [229]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler() #copy,with_mean,with_std
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [230]:
unscaled_inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [231]:
#columns_to_scale = ['Month Value',
       #'Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       #'Children', 'Pets']

## Iteration 2, less columns 

In [232]:
#columns_to_scale = ['Transportation Expense',
 #      'Age', 'Body Mass Index', 'Education',
  #     'Children', 'Pets']
columns_to_omit = ['Reason1', 'Reason2','Reason3','Reason4', 'Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [233]:
absenteeism_scaler = CustomScaler(columns_to_scale)
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [234]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [235]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [236]:
scaled_inputs.shape

(700, 11)

## Split the data & shuffle 

In [237]:
from sklearn.model_selection import train_test_split

In [238]:
train_test_split(scaled_inputs, targets)

[     Reason1  Reason2  Reason3  Reason4  Month Value  Transportation Expense  \
 276        0        0        0        0     0.753746                0.130578   
 613        0        0        0        1    -1.244823                0.387122   
 211        1        0        0        0    -0.388293               -0.654143   
 625        0        0        0        1    -0.959313               -0.654143   
 354        0        0        0        1     1.610276                0.568211   
 ..       ...      ...      ...      ...          ...                     ...   
 227        1        0        0        0    -0.102784                0.356940   
 581        0        0        0        1    -1.530333               -0.654143   
 95         0        0        0        1     1.324766                0.040034   
 81         0        0        0        1     1.324766                0.040034   
 135        0        0        0        1    -1.530333                0.040034   
 
           Age  Body Mass 

In [239]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [240]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [241]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic Regression

In [242]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [243]:
reg = LogisticRegression()

In [244]:
reg.fit(x_train,y_train)

LogisticRegression()

## Checking Model Score

In [245]:
reg.score(x_train,y_train)

0.7732142857142857

In [246]:
model_outputs = reg.predict(x_train)

In [247]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [248]:
np.sum(model_outputs == y_train)

433

In [249]:
model_outputs.shape[0]

560

In [250]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7732142857142857

In [251]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [252]:
reg.intercept_

array([-1.6474549])

In [253]:
feature_name = unscaled_inputs.columns.values #scaled_inputs is an ndarray
feature_name

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [254]:
summary_table = pd.DataFrame(columns=['Feature Name'], data = feature_name)
summary_table

Feature Name
0                  Reason1
1                  Reason2
2                  Reason3
3                  Reason4
4              Month Value
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                    Pets

In [255]:
summary_table['Coefs'] = np.transpose(reg.coef_)

In [256]:
summary_table

Feature Name     Coefs
0                  Reason1  2.800197
1                  Reason2  0.951884
2                  Reason3  3.115553
3                  Reason4  0.839001
4              Month Value  0.158930
5   Transportation Expense  0.605284
6                      Age -0.169891
7          Body Mass Index  0.279811
8                Education -0.210533
9                 Children  0.348262
10                    Pets -0.277396

In [257]:
summary_table.index = summary_table.index + 1


In [258]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

Feature Name     Coefs
1                  Reason1  2.800197
2                  Reason2  0.951884
3                  Reason3  3.115553
4                  Reason4  0.839001
5              Month Value  0.158930
6   Transportation Expense  0.605284
7                      Age -0.169891
8          Body Mass Index  0.279811
9                Education -0.210533
10                Children  0.348262
11                    Pets -0.277396
0                Intercept -1.647455

In [259]:
summary_table = summary_table.sort_index()
summary_table

Feature Name     Coefs
0                Intercept -1.647455
1                  Reason1  2.800197
2                  Reason2  0.951884
3                  Reason3  3.115553
4                  Reason4  0.839001
5              Month Value  0.158930
6   Transportation Expense  0.605284
7                      Age -0.169891
8          Body Mass Index  0.279811
9                Education -0.210533
10                Children  0.348262
11                    Pets -0.277396

In [260]:
summary_table_odds = summary_table.copy()
summary_table is summary_table_odds

False

In [261]:
summary_table_odds["Ddds_Ratio"] = np.exp(summary_table_odds["Coefs"])
summary_table_odds

Feature Name     Coefs  Ddds_Ratio
0                Intercept -1.647455    0.192539
1                  Reason1  2.800197   16.447892
2                  Reason2  0.951884    2.590585
3                  Reason3  3.115553   22.545903
4                  Reason4  0.839001    2.314054
5              Month Value  0.158930    1.172256
6   Transportation Expense  0.605284    1.831773
7                      Age -0.169891    0.843757
8          Body Mass Index  0.279811    1.322880
9                Education -0.210533    0.810152
10                Children  0.348262    1.416604
11                    Pets -0.277396    0.757754

In [262]:
summary_table_odds.rename(columns = {"Ddds_Ratio" : "Odds_Ratio"}, inplace = True)
summary_table_odds

Feature Name     Coefs  Odds_Ratio
0                Intercept -1.647455    0.192539
1                  Reason1  2.800197   16.447892
2                  Reason2  0.951884    2.590585
3                  Reason3  3.115553   22.545903
4                  Reason4  0.839001    2.314054
5              Month Value  0.158930    1.172256
6   Transportation Expense  0.605284    1.831773
7                      Age -0.169891    0.843757
8          Body Mass Index  0.279811    1.322880
9                Education -0.210533    0.810152
10                Children  0.348262    1.416604
11                    Pets -0.277396    0.757754

In [263]:
summary_table_odds.sort_values("Odds_Ratio", ascending=False)


Feature Name     Coefs  Odds_Ratio
3                  Reason3  3.115553   22.545903
1                  Reason1  2.800197   16.447892
2                  Reason2  0.951884    2.590585
4                  Reason4  0.839001    2.314054
6   Transportation Expense  0.605284    1.831773
10                Children  0.348262    1.416604
8          Body Mass Index  0.279811    1.322880
5              Month Value  0.158930    1.172256
7                      Age -0.169891    0.843757
9                Education -0.210533    0.810152
11                    Pets -0.277396    0.757754
0                Intercept -1.647455    0.192539

### Reason 1 = varios disseases, 2 pregnancy / giving birth, 3 poison and peculiar reasons, 4 light diseases
coefficient = 22 times higher reason than when reason 0 because we didn't standarize these dummies

In [264]:
reg.score(x_test, y_test)

0.75

In [266]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [267]:
predicted_proba[:,-1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

In [1]:
import pickle
with open('Model_name_reg_absent', 'wb') as file: #'rb' to unpickle
    pickle.dump(reg, file)
    
with open('Model_name_scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler,file)

NameError: name 'reg' is not defined